# Generated by Django 5.2.7 on 2025-10-22 13:44

import apps.main.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to, verbose_name='Логотип')),
                ('url', models.URLField(blank=True, verbose_name='Сайт')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to, verbose_name='Фото')),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('text', models.TextField(verbose_name='Текст')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to, verbose_name='Логотип')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Слоган')),
                ('copyright_text', models.CharField(blank=True, max_length=255, verbose_name='Текст копирайт')),
                ('tursab_image', models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to, verbose_name='Изображение Турсаб')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('fa_icon', models.CharField(help_text='Напр.: fa-brands fa-instagram', max_length=64, verbose_name='Иконка FA (класс)')),
                ('title', models.CharField(blank=True, help_text='Опционально, для подсказки', max_length=50, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='excursion',
            options={'ordering': ('-created_at',), 'verbose_name': 'Экскурсия', 'verbose_name_plural': 'Экскурсии'},
        ),
        migrations.AddField(
            model_name='excursion',
            name='content_md',
            field=models.TextField(blank=True, verbose_name='Контент (Markdown, без изображений)'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to, verbose_name='Изображение (обложка)'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursion',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ExcursionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.main.models.upload_to, verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Изображение экскурсии',
                'verbose_name_plural': 'Изображения экскурсии',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
